name: benchmark

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.11
  path: ^1.7.0
  random_string: ^2.0.1
  get_storage:
  hive: ^1.4.1+1
  sqflite: ^1.3.1
  shared_preferences: ^0.5.7+3
  fl_chart: 0.1.6
  moor_ffi: ^0.6.0

flutter:
  uses-material-design: true